grafana:
  enabled: true
  adminPassword: "homelab123"
  service:
    type: NodePort
    nodePort: 31000

prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true
  alertmanagerSpec: {}

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false